### ISSUE TITLE
Update to 1.0 please

### ISSUE THREAD

**Issue by Sheridan** [mklierman/SatisfactoryMods#11]
SMR already done. Update mod please

**Comment by Nickola-FR** [comment]
This useful mod is much needed in v1.0, please update.

**Comment by Kupie** [comment]
It's open source, so good luck to you both:

https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/index.html

**Comment by mklierman** [comment]
I was on vacation. Will be updating mods soon.
