### ISSUE TITLE
Remapping keys in Infinite Nudge

### ISSUE THREAD

**Issue by The4thLaw** [mklierman/SatisfactoryMods#18]
Hello,

I recently installed Infinite Nudge and noticed it had a scale feature.
Trouble is: I'm running an AZERTY keyboard and the [ and ] require modifier keys, which are understandably not recognized by the game.

Is there a way to remap the keys? I didn't find one in the mod settings but could easily settle for the ini if it was possible. May I suggest documenting it either in a README or on ficsit.app?

I tried looking at the source code but I guess the mapping from the key to the scaling functions is done in the UE assets.

Thanks

**Comment by mklierman** [comment]
They can be remapped from the vanilla keybinds menu. This is from the mod description:

> All distances and amounts can be adjusted in the Mod Config and all of the hotkeys can be changed in the Vanilla Keybinds menu.
