### ISSUE TITLE
Doggo Transportation is giving me back a statue of the dog, not the dog itself

### ISSUE THREAD

**Issue by Gunsi1973** [mklierman/SatisfactoryMods#20]
Pretty much what the Subject suggest.
When I pick up the dog its in my inventory, when I drop it I just drop a statue. Is this intentional or a bug? I presumed I could collect the doggies and put them eg. in a Zoo or something :)
Great Mods - Love zoop

**Comment by mklierman** [comment]
You need to equip and use it like a berry or nut

**Comment by Gunsi1973** [comment]
Thanks - that did the trick
